export const ROLE_USER = {
  SELLER: 'SELLER',
  BIDDER: 'BIDDER',
  ADMIN: 'ADMIN'
}

export const ARRAY_ROLE_USER = [ROLE_USER.BIDDER, ROLE_USER.SELLER, ROLE_USER.ADMIN]

export const STATUS_USER = {
  VERIFIED: 'VERIFIED',
  NOT_VERIFIED: 'NOT_VERIFIED',
  DISABLED: 'DISABLED'
}

export const ARRAY_STATUS_USER = [STATUS_USER.VERIFIED, STATUS_USER.DISABLED]
